# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ingress-consul
# spec:
#   rules:
#   - http:
#       paths:
#         - path: /
#           pathType: Prefix
#           backend:
#             service:
#               name: frontend
#               port: 
#                 number: 80

#Consul ingress

apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: ingress-gateway
spec:
  listeners:
    - port: 8080
      protocol: http
      services:
        - name: frontend
        
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ingress-gateway
# spec:
#   defaultBackend:
#     service:
#       name: frontend
#       port:
#         number: 8080

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: frontend
#   annotations:
#     kubernetes.io/ingress.class: kong
#     konghq.com/preserve-host: "false"
# spec:
#   rules:
#     - http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: frontend
#                 port:
#                   number: 8080