kind: IngressBackend
apiVersion: policy.openservicemesh.io/v1alpha1
metadata:
  name: osm-ingress
spec:
  backends:
    - name: frontend
      port:
        number: 8080 # targetPort of the service
        protocol: http
  sources:
    - kind: Service
      namespace: default
      name: frontend