global:
  enabled: true
  name: consul
  datacenter: dc1
  acls:
    manageSystemACLs: true
  metrics:
    enabled: true
    enableAgentMetrics: true
server:
  replicas: 3
client:
  enabled: true
connectInject:
  enabled: true
  transparentProxy:
    defaultEnabled: true
  logLevel: debug
ui:
  enabled: true
  service:
    type: LoadBalancer
controller:
  enabled: true
