{
 "title": "master-thesis-grafana-dashboard-for-istio",
 "time": { "from": "2023-01-08T10:35:08.000Z", "to": "2023-01-08T10:45:16.000Z" },
 "panels": [
  {
   "title": "CPU control plane",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{namespace=\"istio-system\",pod=~\"istiod.+\"}[1h])) by (pod)"
    }
   ]
  },
  {
   "title": "Memory control plane",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(rate(container_memory_usage_bytes{namespace=\"istio-system\",pod=~\"istiod.+\"}[1h])) by (pod)"
    }
   ]
  },
  {
   "title": "CPU data plane",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{namespace=\"microservices\"}[1h])) by (pod)"
    }
   ]
  },
  {
   "title": "Memory data plane",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg(rate(container_memory_usage_bytes{namespace=\"microservices\"}[1h])) by (pod)"
    }
   ]
  }
 ]
}