{
 "title": "master-thesis-grafana-dashboard-for-consul",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU control plane",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{namespace=\"consul\",pod=~\"consul-client.+|consul-server.+\"}[1h])) by (pod)"
    }
   ]
  },
  {
   "title": "Memory data plane",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(rate(container_memory_usage_bytes{namespace=\"consul\",pod=~\"consul-client.+|consul-server.+\"}[1h])) by (pod)"
    }
   ]
  },
  {
   "title": "CPU data plane",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{namespace=\"microservices\"}[1h])) by (pod)"
    }
   ]
  },
  {
   "title": "Memory data plane",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "avg(rate(container_memory_usage_bytes{namespace=\"microservices\"}[1h])) by (pod)"
    }
   ]
  }
 ]
}