apiVersion: specs.smi-spec.io/v1alpha4
kind: TCPRoute
metadata:
  name: tcp-echo-route
  namespace: default
spec:
  matches:
    ports: []
---
# Traffic target to allow curl app to access tcp-echo service using a TCPRoute
kind: TrafficTarget
apiVersion: access.smi-spec.io/v1alpha3
metadata:
  name: tcp-access
spec:
  destination:
    kind: ServiceAccount
    name: frontend
    namespace: default
  rules:
  - kind: TCPRoute
    name: tcp-echo-route
  sources:
  - kind: ServiceAccount
    name: frontend-external
